# Generated by Django 3.0.2 on 2024-01-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansade_app', '0003_familleproduit_panier_panierproduit_pointdevente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('base_date', models.DateField()),
            ],
        ),
    ]
